- type: rank
  id: RMCRankVAIMercenary
  name: VAI Mercenary
  prefix: Найм.

- type: rank
  id: RMCRankVAIMedicalSpecialist
  name: VAI Medical Specialist
  prefix: Мед.

- type: rank
  id: RMCRankVAIMachinegunner
  name: VAI Machinegunner
  prefix: Пул.

- type: rank
  id: RMCRankVAIEngineeringSpecialist
  name: VAI Engineering Specialist
  prefix: Инж.

- type: rank
  id: RMCRankVAISynthetic
  name: VAI Synthetic
  prefix: Син.

- type: rank
  id: RMCRankVAITeamLeader
  name: VAI Team Leader
  prefix: Лид.
