- type: rank
  id: RMCRankFLFreelancer
  name: Наемник
  prefix: Наем.

- type: rank
  id: RMCRankFLMedic
  name: Medic
  prefix: Мед.

- type: rank
  id: RMCRankFLLeader
  name: Лидер
  prefix: Барон

- type: rank
  id: RMCRankFLEliteFreelancer
  name: Элита
  prefix: Наем.

- type: rank
  id: RMCRankFLEliteHeavy
  name: Элитный Пулеметчик
  prefix: Тяж.

- type: rank
  id: RMCRankFLEliteEngineer
  name: Элитный Инженер
  prefix: Инж.

- type: rank
  id: RMCRankFLEliteMedic
  name: Элитный Медик
  prefix: Мед.

- type: rank
  id: RMCRankFLEliteLeader
  name: Элитный Лидер
  prefix: Барон
