- type: rank
  id: RMCRankOperator
  name: Оператор
  prefix: ОПР.

- type: rank
  id: RMCRankOperative
  name: Оперативник
  prefix: ОПР.

- type: rank
  id: RMCRankSynthetic
  name: Синтетик
  prefix: Син.
  paygrade: E8

- type: rank
  id: RMCRankSyntheticMG
  name: Синтетик
  prefix: Син.
  paygrade: E9

- type: rank
  id: RMCRankSyntheticColonist
  name: Синтетик
  prefix: Син.
