# TSEPA - (Three Suns Empire Policing Authority) - TSE style Police, like the CMB but for heavy TSE focused colonies. Please change when we have a new name for the sector.

- type: rank
  id: RMCRankTSEPAConstable
  name: Констебль
  prefix: Кстб.

- type: rank
  id: RMCRankTSEPASeniorConstable
  name: Senior Constable
  prefix: Ст. Кстб.

- type: rank
  id: RMCRankTSEPASergeant
  name: Сержант
  prefix: Серж.

- type: rank
  id: RMCRankTSEPAInspector
  name: Инспектор
  prefix: Инсп.

- type: rank
  id: RMCRankTSEPAChiefInspector
  name: Главный Инспектор
  prefix: Гл. Инсп.

- type: rank
  id: RMCRankTSEPACommander
  name: Коммандер
  prefix: Кмдр.

- type: rank
  id: RMCRankTSEPADeputyCommissioner
  name: Заместитель Комиссара
  prefix: Зам. Кмс.

- type: rank
  id: RMCRankTSEPACommissioner
  name: Комиссар
  prefix: Кмс.

