- type: rank
  id: RMCRankNavySeamanRecruit
  name: Матрос-рекрут
  prefix: Мат-Рек.
  paygrade: E1

- type: rank
  id: RMCRankNavySeamanApprentice
  name: Младший Матрос
  prefix: Мл. Мат.
  paygrade: E2

- type: rank
  id: RMCRankNavySeaman
  name: Матрос
  prefix: Мат.
  paygrade: E3

- type: rank
  id: RMCRankNavyPettyOfficer3rdClass
  name: Петти-Офицер III класса
  prefix: ПОIII.
  paygrade: E4

- type: rank
  id: RMCRankNavyPettyOfficer2ndClass
  name: Петти-Офицер II класса
  prefix: ПОII.
  paygrade: E5

- type: rank
  id: RMCRankNavyPettyOfficer1stClass
  name: Петти-Офицер I класса
  prefix: ПОI.
  paygrade: E6

- type: rank
  id: RMCRankNavyChiefPettyOfficer
  name: Чиф-Петти-Офицер
  prefix: ЧПО.
  paygrade: E7

- type: rank
  id: RMCRankNavySeniorChiefPettyOfficer
  name: Старший Чиф-Петти-Офицер
  prefix: СЧПО.
  paygrade: E8

- type: rank
  id: RMCRankNavyCommandSeniorChiefPettyOfficer
  name: Главный Старший Чиф-Петти-Офицер
  prefix: ГСЧПО.
  paygrade: E8

- type: rank
  id: RMCRankNavyMasterChiefPettyOfficer
  name: Мастер Чиф-Петти-Офицер
  prefix: МЧПО.
  paygrade: E9

- type: rank
  id: RMCRankNavyCommandMasterChiefPettyOfficer
  name: Главный Мастер Чиф-Петти-Офицер
  prefix: ГМЧПО.
  paygrade: E9

# Commissioned Officers
- type: rank
  id: RMCRankNavyEnsign
  name: Энсин
  prefix: Энс.
  paygrade: O1

- type: rank
  id: RMCRankNavyLieutenantJuniorGrade
  name: Младший Лейтенант Флота
  prefix: Мл. Лейт.
  paygrade: O2

- type: rank
  id: RMCRankNavyLieutenant
  name: Лейтенант Флота
  prefix: Лейт.
  paygrade: O3

- type: rank
  id: RMCRankNavyLieutenantCommander
  name: Лейтенант-коммандер
  prefix: ЛКМД.
  paygrade: O4

- type: rank
  id: RMCRankNavyCommander
  name: Коммандер
  prefix: КМД.
  paygrade: O5

- type: rank
  id: RMCRankNavyCaptain
  name: Капитан
  prefix: Капитан
  paygrade: O6

- type: rank
  id: RMCRankNavyCommodore
  name: Коммодор
  prefix: КМДР.
  paygrade: O7

- type: rank
  id: RMCRankNavySeniorCommodore
  name: Старший Коммодор
  prefix: Ст. КМДР.
  paygrade: O7

- type: rank
  id: RMCRankNavyRearAdmiralLowerHalf
  name: Младший Контр-адмирал
  prefix: Мл. К-Адм.
  paygrade: O8

- type: rank
  id: RMCRankNavyRearAdmiralUpperHalf
  name: Контр-адмирал
  prefix: К-Адм.
  paygrade: O9

- type: rank
  id: RMCRankNavyViceAdmiral
  name: Вице-адмирал
  prefix: В-Адм.
  paygrade: O9

- type: rank
  id: RMCRankNavyAdmiral
  name: Адмирал
  prefix: Адм.
  paygrade: O10

- type: rank
  id: RMCRankNavyChiefOfNavalOperations
  name: Глава Морских Операций
  prefix: ГМО.
  paygrade: O10
