- type: rank
  id: RMCRankMajorGeneral
  name: Генерал Майор
  prefix: Ген. Майор
  paygrade: O8

- type: rank
  id: RMCRankBrigadierGeneral
  name: Бригадный Генерал
  prefix: Бриг. Ген.
  paygrade: O7

- type: rank
  id: RMCRankColonel
  name: Полковник
  prefix: Полк.
  paygrade: O6

- type: rank
  id: RMCRankLieutenantColonel
  name: Лейтенант-Полковник
  prefix: Подполк.
  paygrade: O5

- type: rank
  id: RMCRankMajor
  name: Майор
  prefix: Майор
  paygrade: O4

- type: rank
  id: RMCRankCaptain
  name: Капитан
  prefix: Капитан
  paygrade: O3

- type: rank
  id: RMCRankFirstLT
  name: Первый Лейтенант
  prefix: 1ый. Лейт.
  paygrade: O2

- type: rank
  id: RMCRankSecondLT
  name: Второй Лейтенант
  prefix: 2ой. Лейт.
  paygrade: O1

- type: rank
  id: RMCRankChiefWarrantOfficer
  name: Старший Уорент-Офицер
  prefix: СтУорОф.
  paygrade: O0-2

- type: rank
  id: RMCRankWarrantOfficer
  name: Уоррент-Офицер
  prefix: УорОф.
  paygrade: O0-1
