# Whisper
- type: rank
  id: RMCRankProvostSectorMarshal
  name: Секторный Маршал
  prefix: Сек. Маршл
  paygrade: O9

# Any admin with high law understanding
- type: rank
  id: RMCRankProvostSeniorMarshal
  name: Старший Маршал
  prefix: Ст. Маршал
  paygrade: O8

# Any admin with low law understanding, or wanting a lower rank
- type: rank
  id: RMCRankProvostMarshal
  name: Маршал
  prefix: Маршал
  paygrade: O7

# Any whitelisted CO
- type: rank
  id: RMCRankProvostDeputyMarshal
  name: Заместитель Маршала
  prefix: Зам. Маршала
  paygrade: O6

# Fax responder
- type: rank
  id: RMCRankProvostCommunicationsOfficer
  name: Communications Officer
  prefix: ComOff.

# Any player with high law understanding
- type: rank
  id: RMCRankProvostChiefInspector
  name: Главный Инспектор
  prefix: Гл. Инспектор
  paygrade: CI

# Any player with medium-low law understanding
- type: rank
  id: RMCRankProvostInspector
  name: Провост Инспектор
  prefix: Провост Инспектор
  paygrade: I

# Any player with low law understanding, with guidance
- type: rank
  id: RMCRankProvostAdvisor
  name: Сержант Майор
  prefix: Серж. Майор
  paygrade: E9E

# Any player with given objective, possible team leader
- type: rank
  id: RMCRankProvostProvostTeamLeader
  name: Мастер Сержант
  prefix: Маст. Серж.
  paygrade: E8

# Any player with given objective, squad member
- type: rank
  id: RMCRankProvostProvostEnforcer
  name: Старший Сержант
  prefix: Ст. Серж.
  paygrade: E6
