- type: job
  parent: CMJobXenoBase
  id: CMXenoLarva
  name: cm-job-name-xeno-larva
  description: cm-job-description-Larva
  playTimeTracker: CMJobXenoLarva
  joinNotifyCrew: false
  supervisors: cm-job-supervisors-queen
  canBeAntag: false
  jobEntity: CMXenoLarva

- type: entity
  parent: CMXenoSpawnPointJobBase
  id: CMSpawnPointLarva
  name: larva spawn point
  components:
  - type: SpawnPoint
    job_id: CMXenoLarva
  - type: Sprite
    layers:
    - sprite: Markers/jobs.rsi
      state: green
    - state: larva

- type: playTimeTracker
  id: CMJobXenoLarva
