- type: rank
  id: RMCRankCMBDeputy
  name: БКМ Заместитель
  prefix: Зам.
  paygrade: БКМЗ

- type: rank
  id: RMCRankCMBMarshal
  name: БКМ Маршал
  prefix: Маршал
  paygrade: БКММ

- type: rank
  id: RMCRankCMBInvestigativeSynthetic
  name: БКМ Следователь-Синтетик
  prefix: Син.

- type: rank
  id: RMCRankCMBRiotControlSynthetic
  name: БКМ Синтетик Подавления Бунтов
  prefix: Син.

- type: rank
  id: RMCRankCMBRiotControlOfficer
  name: БКМ Офицер Подавления Бунтов
  prefix: Оф.

- type: rank
  id: RMCRankCMBMedicalTechnician
  name: БКМ Медицинский Техник
  prefix: Мед.

- type: rank
  id: RMCRankCMBBreachingTechnician
  name: БКМ Техник По Взлому
  prefix: Взлом.

- type: rank
  id: RMCRankCMBSWATSpecialist
  name: БКМ SWAT Специалист
  prefix: Спец.

- type: rank
  id: RMCRankICBAgent
  name: Агент Межзвездного Бюро Торговли
  prefix: Агент

- type: rank
  id: RMCRankICBCorporateLiaison
  name: Корпоративный Связной Межзвездного Бюро Торговли
  prefix: МБТ Пред.
  paygrade: МБТКС

- type: rank
  id: RMCRankIHROObserver
  name: Межзвездный Наблюдатель за Правами Человека
  prefix: "Нблд."
  paygrade: МНПЧ
