- type: rank
  id: RMCRankWeYaOperator
  name: Оператор
  prefix: ОПР.
  paygrade: ЧВК-ОП

- type: rank
  id: RMCRankWeYaEnforcer
  name: Силовик
  prefix: СИЛ.
  paygrade: ЧВК-СЛ

- type: rank
  id: RMCRankWeYaVehicleSpecialist
  name: Специалист Транспорта
  prefix: СПЦТ.
  paygrade: ЧВК-СТ

- type: rank
  id: RMCRankWeYaSupportSpecialist
  name: Специалист Поддержки
  prefix: СПЦП.
  paygrade: ЧВК-СП

- type: rank
  id: RMCRankWeYaMedicalSpecialist
  name: Специалист Медицины
  prefix: СПЦМ.
  paygrade: ЧВК-СМ

- type: rank
  id: RMCRankWeYaWeaponSpecialist
  name: Специалист по Оружию
  prefix: СПЦОР.
  paygrade: ЧВК-СО

- type: rank
  id: RMCRankWeYaXenoSpecialist
  name: Специалист Ксено
  prefix: СПЦКС.
  paygrade: ЧВК-СК

- type: rank
  id: RMCRankWeYaTraumaSurgeon
  name: Trauma Surgeon
  prefix: Док.
  paygrade: ЧВК-ДОК

- type: rank
  id: RMCRankWeYaCorporateTechnician
  name: Корпоративный Техник
  prefix: ТЕХ.
  paygrade: ЧВК-ТЕХ

- type: rank
  id: RMCRankWeYaEliteResponder
  name: Элитный Оператор
  prefix: ЭОП.
  paygrade: ЧВК-ЭОП

- type: rank
  id: RMCRankWeYaEliteMedic
  name: Элитный Медик
  prefix: ЭЛМ.
  paygrade: ЧВК-ЭЛМ

- type: rank
  id: RMCRankWeYaEliteGunner
  name: Элитный Стрелок
  prefix: ЭЛС.
  paygrade: ЧВК-ЭЛС

- type: rank
  id: RMCRankWeYaPMCSynthetic
  name: Synthetic
  prefix: SYN.
  paygrade: PMC-SYN

- type: rank
  id: RMCRankWeYaTeamLeader
  name: Лидер Группы
  prefix: ЛИД.
  paygrade: ЧВК-ЛИД

- type: rank
  id: RMCRankWeYaForceLeader
  name: Force Leader
  prefix: FL.
  paygrade: PMC-FL

- type: rank
  id: RMCRankWeYaEliteTeamLeader
  name: Элитный Лидер Группы
  prefix: ЭЛИД.
  paygrade: ЧВК-ЭЛГ

- type: rank
  id: RMCRankWeYaSiteDirector
  name: ЧВК Директор Объекта
  prefix: Директор
  paygrade: ЧВК-ДИР

- type: rank
  id: RMCRankWeYaForceCommand
  name: ЧВК Командование Сил
  prefix: КОC.
  paygrade: ЧВК-КОС

- type: rank
  id: RMCRankWeYaWhiteout
  name: Whiteout Team Combat Unit
  prefix: WO.
  paygrade: ???
